columns:

 
  Item_Weight:float64
 
  Item_Visibility:float64
   
  Item_MRP:float64
  
   
  


numerical_columns:
  

Outlet_Establishment_Year:int64 

categorical_columns:


Item_Identifier:object 
Item_Fat_Content:object
Item_Type:object
Outlet_Identifier:object
Outlet_Size:object 
Outlet_Location_Type:object 
Outlet_Type:object 
stores:Category 

target_column:   Item_Outlet_Sales:float64

domain_value:
  stores:
    - STORE ID
    - LOW STORE
    - MEDIUM STORE
    - HIGH STORE
    - GROCERY STORE OR SUPERMARKET 